from dealwatcherer.persistence.base import Base
from dealwatcherer.persistence.models import (
    CashbackQuote,
    CanonicalProduct,
    DeliveryEvent,
    EffectivePriceSnapshot,
    NotificationRule,
    PriceObservation,
    ProductCandidate,
    StoreAdapterBinding,
    TaskRun,
    User,
    UserPreference,
    WatchGroup,
    WatchGroupMember,
    WatchGroupRun,
    WatchTarget,
    WatchTask,
)

__all__ = [
    "Base",
    "CashbackQuote",
    "CanonicalProduct",
    "DeliveryEvent",
    "EffectivePriceSnapshot",
    "NotificationRule",
    "PriceObservation",
    "ProductCandidate",
    "StoreAdapterBinding",
    "TaskRun",
    "User",
    "UserPreference",
    "WatchGroup",
    "WatchGroupMember",
    "WatchGroupRun",
    "WatchTarget",
    "WatchTask",
]
